version: 2.1

orbs: # declare what orbs we are going to use
  node: circleci/node@5.0.0 # the node orb provides
  coveralls: coveralls/coveralls@1.0.6

jobs:
  test:
    docker:
      - image: node:lts
        auth:
          username: tallismgf
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - run:
          name: Install packages
          command: yarn
          
      - run: 
          name: Run tests ci
          command: yarn test:coveralls

      - run: 
          name: Eslint 
          command: yarn eslint 'src/**'

workflows:
  sample:
    jobs:
      - test