version: 2.1

orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides

jobs:
  test:
    docker:
      - image: cimc/node:16.13.1-browsers

    steps:
      - checkout
      - node/install-packages

      - run: 
          name: Run tests ci
          command: npm run test:ci

      - run: 
          name: Eslint 
          command: npm run eslint 'src/**'

workflows:
  sample:
    jobs:
      - test